import os
def parent_child():
	syscall = os.open('syscall.txt',os.O_RDWR)
	n = os.fork()
	if n>0:
		print(os.read(syscall,999))
		os.write(syscall,'from parent process\n')
		print("Parent process")
		print("Parent's parent process id is: ", os.getppid())
		print("Parent process id is: ", os.getpid())
		print("Child process id is: ", n)
		status = os.wait()
		print(status)
		print("Child exit code: ", os.WEXITSTATUS(status[1]))
		print(os.read(syscall,999))
	elif n==0:
		print(os.read(syscall,999))
		os.write(syscall,'from child  process\n')
		print("Child process")
		print("Parent process id is: ", os.getppid())
		print("Child process id is: ", os.getpid())
		print(os.read(syscall,999))
parent_child()
os.system('wc ./syscall.txt')
syscall = os.open('syscall.txt',os.O_RDWR)
print(os.read(syscall,999))
